/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wizwa9381
 */
public class MakingPurchases extends javax.swing.JFrame {

    /**
     * Creates new form MakingPurchases
     */
    public MakingPurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calcButton = new javax.swing.JButton();
        kitkatLabel = new javax.swing.JLabel();
        kitkatAmountTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        aeroLabel = new javax.swing.JLabel();
        aeroAmountTextField = new javax.swing.JTextField();
        marsBarLabel = new javax.swing.JLabel();
        marsBarAmountTextField = new javax.swing.JTextField();
        subtotalLabel = new javax.swing.JLabel();
        taxesLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(80, 200, 140));

        calcButton.setText("Calculate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        kitkatLabel.setText("KitKat:   $0.99");

        kitkatAmountTextField.setText("0");
        kitkatAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitkatAmountTextFieldActionPerformed(evt);
            }
        });

        amountLabel.setText("Amount");

        aeroLabel.setText("Aero:   $0.99");

        aeroAmountTextField.setText("0");
        aeroAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeroAmountTextFieldActionPerformed(evt);
            }
        });

        marsBarLabel.setText("Mars Bar:   $1.29");

        marsBarAmountTextField.setText("0");
        marsBarAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsBarAmountTextFieldActionPerformed(evt);
            }
        });

        subtotalLabel.setText("Subtotal: $0.00");

        taxesLabel.setText("Taxes (13%) : $0.00");

        totalLabel.setText("Total: $0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(amountLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(calcButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kitkatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(kitkatAmountTextField))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(aeroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(aeroAmountTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marsBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marsBarAmountTextField))
                        .addContainerGap(20, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel)
                    .addComponent(taxesLabel)
                    .addComponent(subtotalLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitkatLabel)
                    .addComponent(aeroLabel)
                    .addComponent(marsBarLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitkatAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountLabel)
                    .addComponent(aeroAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marsBarAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(subtotalLabel)
                .addGap(18, 18, 18)
                .addComponent(taxesLabel)
                .addGap(18, 18, 18)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(calcButton)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitkatAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitkatAmountTextFieldActionPerformed

    }//GEN-LAST:event_kitkatAmountTextFieldActionPerformed

    private void aeroAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeroAmountTextFieldActionPerformed

    }//GEN-LAST:event_aeroAmountTextFieldActionPerformed

    private void marsBarAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsBarAmountTextFieldActionPerformed

    }//GEN-LAST:event_marsBarAmountTextFieldActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        //variables
        double kitkatTotal,aeroTotal,marsBarTotal,tax,totalWithoutTax,totalWithTax;
        double kitkat = 0.99;
        double marsBar = 1.29;
        double aero = 0.99;
        int kitkatAmount,aeroAmount,marsBarAmount,taxTotal;
        //calculations
        kitkatAmount = Integer.parseInt(kitkatAmountTextField.getText());
        kitkatTotal = kitkatAmount*kitkat;
        aeroAmount = Integer.parseInt(aeroAmountTextField.getText());
        aeroTotal = aeroAmount*aero;
        marsBarAmount = Integer.parseInt(marsBarAmountTextField.getText());
        marsBarTotal = marsBarAmount*marsBar;
        totalWithoutTax = marsBarTotal + aeroTotal + kitkatTotal;
        tax = (marsBarTotal + aeroTotal + kitkatTotal)*0.13;
        tax = tax*100;
        taxTotal = (int) tax;
        tax = taxTotal;
        tax = tax/100;
        totalWithTax = marsBarTotal + aeroTotal + kitkatTotal + tax;
        //actions
        subtotalLabel.setText("Your total without tax is $" + totalWithoutTax);
        taxesLabel.setText("The tax amount is $" + tax);
        totalLabel.setText("Your grand total is $" + totalWithTax);
    }//GEN-LAST:event_calcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingPurchases().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aeroAmountTextField;
    private javax.swing.JLabel aeroLabel;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton calcButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kitkatAmountTextField;
    private javax.swing.JLabel kitkatLabel;
    private javax.swing.JTextField marsBarAmountTextField;
    private javax.swing.JLabel marsBarLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel taxesLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
